### ISSUE TITLE
1.0.10引入项目后没有效果

### ISSUE THREAD

**Issue by fanaishan** [lxchinesszz/tomato#12]
**描述错误**

1.0.10引入项目后没有效果

**重现**
将项目打包后,引入本地JAR打包后运行,没有打印出logo,应该是没有正常启用,这个如何处理?

**Comment by lxchinesszz** [comment]
可以先这样启用，下个版本你反馈的修复。 10版本支持从httpHeader中获取token，如果用不到可以先用老版本。


@Import({TomatoAutoConfiguration.class})
@SpringBootApplication
public class AddressApplication {


public static void main(String[] args) {
run(AddressApplication.class, args);
}
}



| |
刘鑫
|
|
***@***.***
|
签名由网易邮箱大师定制


在2023年03月15日 ***@***.***> 写道：

描述错误

1.0.10引入项目后没有效果

重现
将项目打包后,引入本地JAR打包后运行,没有打印出logo,应该是没有正常启用,这个如何处理?

**Comment by wodekehu** [comment]
你这个方法不行，@import({TomatoAutoConfiguration.class})
这样是不行的，springboot2.7版本。

**Comment by tianxiakeji** [comment]
同样遇到SpringBoot2.7.3。另外1.0.9-RELEASE  1.0.9.RELEASE下载不到

**Comment by lxchinesszz** [comment]
可以先这样启用，下个版本你反馈的修复。 10版本支持从httpHeader中获取token，如果用不到可以先用老版本。


@Import({TomatoAutoConfiguration.class})
@SpringBootApplication
public class AddressApplication {


public static void main(String[] args) {
run(AddressApplication.class, args);
}
}



















在 2023-07-13 11:34:01，"小生命" ***@***.***> 写道：

同样遇到SpringBoot2.7.3。另外1.0.9-RELEASE 1.0.9.RELEASE下载不到

**Comment by lxchinesszz** [comment]
> 同样遇到SpringBoot2.7.3。另外1.0.9-RELEASE 1.0.9.RELEASE下载不到

2.7开始 spring就不太支持，/META-INF/spring.factories。可能和这个有关系。是版本的问题导致的。

**Comment by lxchinesszz** [comment]
已修复



在 2023-07-19 14:32:10，"刘鑫" ***@***.***> 写道：


可以先这样启用，下个版本你反馈的修复。 10版本支持从httpHeader中获取token，如果用不到可以先用老版本。


@Import({TomatoAutoConfiguration.class})
@SpringBootApplication
public class AddressApplication {


public static void main(String[] args) {
run(AddressApplication.class, args);
}
}



















在 2023-07-13 11:34:01，"小生命" ***@***.***> 写道：

同样遇到SpringBoot2.7.3。另外1.0.9-RELEASE 1.0.9.RELEASE下载不到
