### ISSUE TITLE
redisTemplate.opsForValue().setIfAbsent(uniqueCode, TomatoConstant.DEFAULT_VALUE)

### ISSUE THREAD

**Issue by lianbitangjin** [lxchinesszz/tomato#3]
设置超时时间是一个单独的方法，我看redis的setIfAbsent提供了超时时间的设置

  @Nullable
    Boolean setIfAbsent(K var1, V var2);

    @Nullable
    Boolean setIfAbsent(K var1, V var2, long var3, TimeUnit var5);

**Comment by lxchinesszz** [comment]
> 设置超时时间是一个单独的方法，我看redis的setIfAbsent提供了超时时间的设置
> 
> @nullable
> Boolean setIfAbsent(K var1, V var2);
> 
> ```
> @Nullable
> Boolean setIfAbsent(K var1, V var2, long var3, TimeUnit var5);
> ```

谢谢这个API,还没用过。不过看起来很棒。准备采纳您的建议。

**Comment by lxchinesszz** [comment]
已经采纳了你的建议,新版本1.0.3.RELEASE

**Comment by lxchinesszz** [comment]
> 设置超时时间是一个单独的方法，我看redis的setIfAbsent提供了超时时间的设置
> 
> @nullable
> Boolean setIfAbsent(K var1, V var2);
> 
> ```
> @Nullable
> Boolean setIfAbsent(K var1, V var2, long var3, TimeUnit var5);
> ```

已经采纳了你的建议,新版本1.0.3.RELEASE
