### ISSUE TITLE
token为空时报空指针异常

### ISSUE THREAD

**Issue by ruansheng8** [lxchinesszz/tomato#4]
token为空的时候,在设置token值的时候会直接报空指针,这里应该把StaticContext.setToken(tomatoToken);方法放到下面执行
![image](https://user-images.githubusercontent.com/24709538/85225550-c1a66d80-b404-11ea-9b52-e52f9ae855cf.png)

**Comment by lxchinesszz** [comment]
非常感谢你的提醒，已经修复了这个bug,新版本1.0.3.RELEASE。
