### ISSUE TITLE
这样设置锁不具备原子性

### ISSUE THREAD

**Issue by zqsds** [lxchinesszz/tomato#6]
![image](https://user-images.githubusercontent.com/24616950/111434851-04e70000-873b-11eb-89d6-ccd1de43007a.png)
建议用org.springframework.data.redis.core.ValueOperations#setIfAbsent(K, V, long, java.util.concurrent.TimeUnit)

**Comment by lxchinesszz** [comment]
这个问题已经修复过了，请见最新版本1.0.5-RELEASE
